version: '3'
services:
  nginx:
    depends_on:
      - backend
      - frontend
    restart: always
    image: 'cwcan/explorer-nginx'
    mem_limit: 128m
    hostname: nginx
    ports:
      - '80:80'
    volumes:
      - backend_data:/backend_data
  backend:
    image: 'cwcan/explorer-backend'
    mem_limit: 128m
    hostname: backend
    ports:
      - "8000:8000"
    restart: always
    entrypoint: ./docker-entrypoint.sh
    command: uwsgi --ini uwsgi.ini
    environment:
      - PGUSER=$PGUSER
      - PGHOST=$PGHOST
      - PGDATABASE=$PGDATABASE
      - PGPASSWORD=$PGPASSWORD
      - PGPORT=$PGPORT    
    volumes:
      - backend_data:/app
  frontend:
    image: 'cwcan/explorer-frontend'
    mem_limit: 128m
    hostname: frontend
    ports:
      - "3000:3000"
volumes:
  backend_data: