name: Build and Test Explorer Docker (CI)
on:
  push:
    branches-ignore:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker build -t cwcan/react-test -f ./frontend/Dockerfile.dev ./frontend
      - run: docker run -e CI=true cwcan/react-test npm test

      - run: docker build -t cwcan/explorer-frontend ./frontend
      - run: docker build -t cwcan/explorer-backend ./backend
      - run: docker build -t cwcan/explorer-nginx ./nginx

      - run: docker push cwcan/explorer-frontend
      - run: docker push cwcan/explorer-backend
      - run: docker push cwcan/explorer-nginx
